name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go mod download

    - name: Linting with Golangci-Lint
      run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
      # Replace the below line with your custom golangci-lint configuration, if needed
      run: golangci-lint run ./...

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...
